### ISSUE TITLE
Unhandled Exception - Windows Server 2008 64bit

### ISSUE THREAD

**Issue by vinhduong** [Apr4h/CobaltStrikeScan#5]
Please help me,
I scanned this tool on my server, but it's failed. You can see the attached pitures
![Screen Shot 2020-10-28 at 16 41 24](https://user-images.githubusercontent.com/25747761/97419742-ff7c4b00-193c-11eb-9387-3e63a6701ac8.png)

**Comment by Apr4h** [comment]
I'm going to test the tool on a 64bit Server 2008 VM to see if I can recreate the issue. It would be helpful to know what version of the .NET Framework you have installed on your server.

**Comment by Apr4h** [comment]
After doing some testing, I'll definitely need more information to be able to help you here. I installed .NET Framework version 4.6 (This is a stated requirement for CobaltStrikeScan) on a freshly installed Windows Server 2008 64 bit machine then ran the exact same command with no errors, as per the screenshot below. I also used  [New-InjectedThread.ps1](https://github.com/jaredcatkinson/PSReflect-Functions) to test that the tool runs successfully if it does detect injection.

Next step definitely seems to be checking what version of the .NET framework you have installed...

![image](https://user-images.githubusercontent.com/42139404/97720127-cea43d80-1b17-11eb-9e2d-132a3b008dc4.png)

**Comment by vinhduong** [comment]
I used .NetFramework 4.7 on Window Server 2008 64bit.
![Screen Shot 2020-11-02 at 15 43 04](https://user-images.githubusercontent.com/25747761/97848272-6b86f680-1d23-11eb-82d1-d9e6fe31fa10.png)
Could you please help me to solve this problem?

**Comment by Apr4h** [comment]
I'm still unable to recreate the error you're seeing after installing .NET framework version 4.7. Still detects injected threads just fine from an elevated PowerShell or cmd prompt with the same command-line options as you. Are you using the most current release of CobaltStrikeScan? Did you download it and compile yourself? If so, did you modify any of the code? 

![image](https://user-images.githubusercontent.com/42139404/97868687-0a314880-1d60-11eb-8012-de0cdabc6841.png)

**Comment by vinhduong** [comment]
I've downloaded https://github.com/Apr4h/CobaltStrikeScan/releases/download/1.0.1/CobaltStrikeScan.zip.
I ran CobaltStrikeScan.exe on a VM that has the artifacts of CobalStrike. But I got the result (in the attached picture).
![Screen Shot 2020-11-03 at 10 23 17](https://user-images.githubusercontent.com/25747761/97947179-17c9eb00-1dbf-11eb-912e-e00621980b9c.png)

Could you please help me to know this problem? The result that I had was wrong?
Thank you for supporting me.

**Comment by Apr4h** [comment]
It looks like CobaltStrikeScan is working properly from your screenshot. The tool works by detecting the reflective injection method (OFTEN BUT NOT ALWAYS) used to load the Cobalt Strike beacon into memory before YARA scanning that process' memory for beacon signatures. If the beacon was run from a stageless executable, or for whatever reason, classic / reflective process injection did not occur, CobaltStrikeScan will not detect it in memory. 

I might eventually add an option to run the YARA scan against ALL process memory instead of just those with process injection, but currently the tool does not do that.

If you know the process under which the Beacon is running, you could dump all memory associated with that process then use CobaltStrikeScan's `-f` option on the memory dump to scan for the Beacon and parse its config. Using procdump from Sysinternals, this would look like `procdump -ma <PID>`

**Comment by vinhduong** [comment]
I've just used procdump and CobaltStrike -f option to get the right result. You can see in the attached picture. I hope the next version of CobaltStrikeScan can scan ALL process.
Thank you for supporting.
![messageImage_1604380601440](https://user-images.githubusercontent.com/25747761/97954466-266fcc80-1dd6-11eb-88ca-c1aefdb50998.jpg)
